### ISSUE TITLE
Boot error game.

### ISSUE THREAD

**Issue by damoshack54** [nikhilpatidar/wonton-bot#1]
Good evening, I installed everything but when I start everything this error appears. Could someone help me understand better what is missing? Thanks..

PS C:\Users\CityHall\Documents\GitHub\wonton-bot> & C:/Users/CityHall/AppData/Local/Programs/Python/Python312/python.exe c:/Users/CityHall/Documents/GitHub/wonton-bot/main.py
TgCrypto is missing! Pyrogram will work the same, but at a much slower speed. More info: https://docs.pyrogram.org/topics/speedups
Traceback (most recent call last):
  File "c:\Users\CityHall\Documents\GitHub\wonton-bot\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "c:\Users\CityHall\Documents\GitHub\wonton-bot\bot\utils\__init__.py", line 7, in <module>
    if not os.path.exists(path="sessions"):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: nt._path_exists() takes no keyword arguments

**Comment by nikhilpatidar** [comment]
Install TgCrypto using command 
`pip install TgCrypto`
and add session before you run, or if you already have sessions put them in the main directory inside sessions folder.
