### ISSUE TITLE
Problem starting.

### ISSUE THREAD

**Issue by damoshack54** [nikhilpatidar/wonton-bot#3]
PS C:\Users\CityHall\Documents\GitHub\wonton-bot> & C:/Users/CityHall/AppData/Local/Programs/Python/Python312/python.exe c:/Users/CityHall/Documents/GitHub/wonton-bot/main.py
Traceback (most recent call last):
  File "c:\Users\CityHall\Documents\GitHub\wonton-bot\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "c:\Users\CityHall\Documents\GitHub\wonton-bot\bot\utils\__init__.py", line 7, in <module>
    if not os.path.exists(path="sessions"):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: nt._path_exists() takes no keyword arguments
PS C:\Users\CityHall\Documents\GitHub\wonton-bot>

**Comment by nikhilpatidar** [comment]
[HERE](https://github.com/nikhilpatidar/wonton-bot/issues/1#issuecomment-2336478053)
